import{a as c,i as f}from"./assets/vendor-c619e5f4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function u(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=u(t);fetch(t.href,o)}})();c.defaults.headers.common["x-api-key"]="live_1BX1oIt1NQtkjIl2oGjUV7LNDkwF94yk8hbqyczxZPcwQRJUSZEyDT1h7onEr95m";function m(){return c.get("https://api.thecatapi.com/v1/breeds")}function p(e){const r=new URLSearchParams({breed_ids:e});return c.get(`https://api.thecatapi.com/v1/images/search?${r}`)}const n={breedsList:document.querySelector(".breed-select"),loader:document.querySelector(".loader"),catInfo:document.querySelector("div.cat-info")};L();n.breedsList.addEventListener("change",h);function h(e){y(e.target.value)}function y(e){d(),n.catInfo.innerHTML="",p(e).then(({data:[r]})=>{n.catInfo.innerHTML=g(r),n.catInfo.querySelector(".cat-info-image").addEventListener("load",i)}).catch(r=>{i(),l(r)})}function L(){d(),m().then(({data:e})=>{n.breedsList.innerHTML=e.map(r=>`<option value="${r.id}">${r.name}</option>`).join(""),i(),n.breedsList.classList.remove("visually-hidden")}).catch(e=>{i(),l(e)})}function g(e){return`<div class="cat-info-card">
            <img class="cat-info-image" src="${e.url}" alt="cat" />
            <div class="cat-info-holder">
              <h2 class="cat-info-title">${e.breeds[0].name}</h2>
              <p class="cat-info-text">${e.breeds[0].description}</p>
              <p class="cat-info-text"><b>Temperament:</b> ${e.breeds[0].temperament}</p>
            </div>
          </div>`}function d(){n.loader.classList.remove("visually-hidden")}function i(){n.loader.classList.add("visually-hidden")}function l(e){f.show({color:"red",title:"Ooops! error occured",message:`${e.name}: ${e.message}`,position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
